language: java
jdk: oraclejdk8
before_install:
- chmod +x mvnw
script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: releases
  api_key:
    secure: ZTaq+EAGzB0t6uViO76we43Efc1Ldv6zXvduHAa52Gn3zi1y5X++kMjFuBd2X+o0NeDRqReXzgNx24Cxe6HKJ2btEJf+ctJP0RcXhLlGskVjyJeNCeyxGYJBKds7dC5FzuILcXmfgP6UyAPHJ4OBpb2C4PUxnl48hYMyOTDOn93erKg9wtc7ModMpz1dc8WcKlS+/WPav67QzN3aVlaKgntNivuHzNCTN6AaTYXUzAR/a15DTYRZ5Cl16xezYtOK5g3bUZ6n2RYfCzGq+Vp8ky69+qWgCTM33vUZDsWjZncMrShsOTNnZzTnfWRTDFd0LJzv0qKrHk7Ri1cVSWDwH0Br5is5NnS5g8Li4EYkJC1cAHqpI85raM0tS07xnafhrSD1MlncZ3LTkOPZxSUwzDy4o7CFatOTuhpWsRj8XPT/JnPBtTYlpG/3NTvg5IBSCOQcpKdcu1rF+eLslNpBUV6fTmnUpXiODH9vTBwT2NIF/Ir9sTpnB2f8sa86jdfXMo1u2dxOanexici1rDDILwU3t7NU+nn2ivtM/isK6C0ToaVeMXPY1XmTmOexbQ22ltd2QoldS+pLVSqcngamz9hVpgnvIJyqjzYKQzIzPa1YNP71t23UgpEMaKFqKX1Hjx45uTJIP26DCBOOyYyrH9axayNXT11sDwswequaHsY=
  file: "/home/travis/.m2/repository/com/dxc/test/app/SimpleRESTService/0.0.1-SNAPSHOT/SimpleRESTService-0.0.1-SNAPSHOT.jar"
  on:
    repo: sprhegde/REPOSITORY1
    all_branches: true
    tags: true
    
sudo: required
dist: trusty
group: deprecated-2017Q4

# Cache Gcloud SDK between commands testing
cache:
 directories:
  - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  
after_deploy:
  - bash <(curl -s https://codecov.io/bash)
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl
  
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  
  - export SAMPLE=gcr.io/voltaic-azimuth-192414/simple-rest-service
  - docker build -t $SAMPLE:$COMMIT .
  - docker tag $SAMPLE:$COMMIT $SAMPLE:$TAG
  
  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json

  - gcloud --quiet config set project voltaic-azimuth-192414
  - gcloud --quiet config set compute/zone us-central1-a
  - docker push $SAMPLE