language: java
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: releases
  api_key:
    secure: "MIIEpAIBAAKCAQEA1PYJfdaEMtnDzLHdJDDlYUcL4IWszdb5FIXc5K2VWjulkdW3
44Tt7h+/SmAkxgQ6clmhI1UXfEG0AapF0vEJs5Q09ccIx5UiL6RQmMq0zZWaffeY
Y97hgxP1xdco1OzqDsnWXCAiY2HWDzKfKI2wcPJCAC2a7o//fiECF2eN34kHlhG4
IS2AKJxLzjYzp/jIQdfx0hh39Y2lgnPQ1Q8HnNRRUE/PYu+zV/638vl6JgMaAW1I
Ur6F8UBPTdOYCcsGbwJMSiGYMAcGzilKudMYRvzYcD37LSpeyFun3rZUBmcFzGcW
DO71lqavG+8wiWhUkYJO6kQfKUutDuuTQbHaLwIDAQABAoIBAQCMdkNIZqcHSy6j
4mSzrDR+9vdUfZa+pZ3f9XL+uacavuCz0bzaKiEswG/RRJy8pqlOJuPrhAJbiJKL
zp0DRsxZT9WmjkKyMSE9PymRvZGHT7d4gkhXBvjDFfUzKnjaB/FRE7t5RBCqcCta
Fs93Vg0cUg1KRMo9s2iW7nqMqVagKnN7f+uMRUJhi16oSk4uBa4c++FDcU8BQJlI
Mm7Sadisu+Gi83/kGs/gm/2NeLVKZZbm4tI6l7jqVLWd2meG3kVo8R5BLMlSWjGj
FUstOikkuWHe+CB5FYpmz6WpD6my/PavPgrXSAWSHOaBCayZa/8oj4kPolf0035d
1Ql8k+fxAoGBAOtN3McDmlQZAP8gM4RqBhZgRlRhLzzilTa4DQg6CEGJOjC5/ZlQ
tFXAr8zR5iNvwKPVELWAb06lF6cx3pDeORUbBecLWkpqae6LgjtMRgFQJ9vF1xdS
H5ErryWbN0F54hQrQHylPyfcyh43Xhm75cgAMQlyHsgkybCmGJhngKjdAoGBAOex
GGnfEMUK6ugeuyO+p1N5iWGnJQg4rK6/Vxhc6KVqz7v8KsyAZT+mqOnpkdLx2F9h
l+u7QoiBLZKSea5EnGxyYFiU3ByuPzOjRrzIwmmWdc+kSkC5EkrF6rn0Ds29Mnub
giWIOBV+DgahN3NKrnQ8O5L2YOvZ+gNp59GcfBh7AoGBALADI1XfFQ85UOyGquKu
6HTOeW1e8RXrK9Ctpln0Bv725odSaSfJHcxTgW2FyU/SpVgn5gLO2vQKPII9pI3b
HPnzp9unO1gU976PrtAqgucyjU4xVG7GaISQF8jarV+WC44ouGlEttRbrPkjU4mO
axjLQ+Mb8XinRBOWeyltquklAoGAa98/X6OU2jjwD+ym8siEfU/7z7STgFVqyN2b
PmObidDGMV8Byj8JZO5CfM3bsBwbwqTcp8uC+a0zO6fo8WNOdQt3oiaEqPHTyUX+
3EyYf7Km3Ws/iwzf4GJvm+5uqgmppHVNzg2zFwaenyWWfJ5LxSB6GD2P+J9/UPGR
Fj3GZVsCgYAn2bN0cYiAdCNbdB7QQblfx2x3Qt15kG5Jk7uX/4XD8vSPrkjdCqiN
b7GJ5pnL8s3OOqgPZsksfBgs1BFcMPJ8w3rKj691KyL+VwWDBRrsUJmRAeSBEYls
c5I3NFOOtlONSG7sTvxFQEEoMcZlYQNyprfq1adtjBogv9Arq7B7Kw==" 
  file: $TRAVIS_BUILD_DIR/GitHubApp-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
