language: java
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: releases
  user: "sprhegde"
  password: "Shiva123"
  file: "GitHubApp-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
